### ISSUE TITLE
Sample code is not working - API returns blank line before start of XML document

### ISSUE THREAD

**Issue by starrychloe** [BambooHR/bhr-api-php#8]
The sample code gives an error:

```
PHP Warning:  SimpleXMLElement::__construct(): Entity: line 2: parser error : XML declaration allowed only at the start of the document in /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php on line 66
PHP Warning:  SimpleXMLElement::__construct(): <?xml version="1.0"?> in /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php on line 66
PHP Warning:  SimpleXMLElement::__construct():      ^ in /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php on line 66
PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php:66
Stack trace:
#0 /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php(66): SimpleXMLElement->__construct('?<?xml version=...')
#1 /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php(93): BambooHR\API\BambooHTTPResponse->getContentXML()
#2 /cygdrive/c/Users/Chloe/workspace/Teads/synchronize.php(12): BambooHR\API\BambooHTTPResponse->getContent()
#3 {main}
  thrown in /cygdrive/c/Users/Chloe/workspace/Teads/bhr-api-php/BambooHR/API/API.php on line 66
```

This is how I had to work around it

```
	public function getContentXML() {
		if(!$this->isError() && strpos($this->headers['Content-Type'], 'text/xml') !== false) {
		  $content = $this->content;
      $content = trim($content); # stop off the blank line at the beginning
			return new \SimpleXMLElement($content);

```

**Comment by jlesueur** [comment]
@starrychloe Thanks for pointing this issue out. This has been fixed, and your workaround should no longer be necessary. Please let us know if you see any others.
